### ISSUE TITLE
Error reaching AirSim server (msgpackrpc.error)

### ISSUE THREAD

**Issue by luis-bernard** [Microsoft/AirSim#1141]
Hello again!

I am using UE 4.18 on Windows 10. The error is similar to the one in the following issue but I couldn't fix it: https://github.com/Microsoft/AirSim/issues/609

The error I am getting is:
WARNING:tornado.general:Connect error on fd 6032: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 6032: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 6032: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 6032: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 6032: WSAECONNREFUSED
Retry connection over the limit
Traceback (most recent call last):
  File "E:\Documents\Unreal Projects\PythonTrain\Content\Scripts\comm2.py", line 189, in begin_play
    self.client.confirmConnection()
  File "E:\Documents\Unreal Projects\PythonTrain\Content\Scripts\AirSimClient.py", line 445, in confirmConnection
    home = self.getHomeGeoPoint()
  File "E:\Documents\Unreal Projects\PythonTrain\Content\Scripts\AirSimClient.py", line 454, in getHomeGeoPoint
    return GeoPoint.from_msgpack(self.client.call('getHomeGeoPoint'))
  File "E:\Documents\Unreal Projects\PythonTrain\Plugins\UnrealEnginePython\Binaries\Win64\Lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "E:\Documents\Unreal Projects\PythonTrain\Plugins\UnrealEnginePython\Binaries\Win64\Lib\site-packages\msgpackrpc\future.py", line 43, in get
    raise self._error
msgpackrpc.error.TransportError: Retry connection over the limit

I am trying to run AirSim through UnrealEnginePython plugin. The function MultirotorClient() works but the function confirmConnection() leads to the error.

**Comment by sytelus** [comment]
The message basically means client is not able to find server - usually because you are not running AirSim. Previously (before v1.2), we had different ports for car and multirotor. From v1.2 onwards, we have same port so you shouldn't get this error in v1.2 as long as you are running AirSim.

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
