### ISSUE TITLE
msgpackrpc.error.RPCError

### ISSUE THREAD

**Issue by showaykerker** [Microsoft/AirSim#1152]
Hi, I'm working on a project on Win10 which gets 4 images from 4 threads at the same time.
I added a thread lock when I call MultirotorClient.simGetImages API to keep threads from accessing this API at the same time ( or is it not necessary ? ).
However, after 1 time success in getting images from cameras, I've experienced this error as below, and I'm wondering how to fix it.

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\ncrl\Desktop\Airsim\airsim_drone\ddpg\AirsimEnv.py", line 44, in get_data_from_airsim
>     img = self.client.simGetImages(ImageRequest(i+5, AirSimImageType.DepthPerspective, True))
>   File "C:\Users\ncrl\Desktop\Airsim\airsim_drone\ddpg\AirSimClient.py", line 491, in simGetImages
>     responses_raw = self.client.call('simGetImages', requests)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\msgpackrpc\session.py", line 41, in call
>     return self.send_request(method, args).get()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\msgpackrpc\future.py", line 45, in get
>     raise error.RPCError(self._error)
> msgpackrpc.error.RPCError: rpclib: function 'simGetImages' (called with 1 arg(s)) threw an exception. The exception contained this information: bad cast.

Please let me know if I did anything wrong, thanks :)

**Comment by showaykerker** [comment]
Will, it turns out that I was simply forgetting to add pass the ImageRequest as a list,
so I modified as below 
`
img = self.client.simGetImages([ImageRequest(i+5, AirSimImageType.DepthPerspective, True)])
`
And the RPCError never shows up again :)
