### ISSUE TITLE
environment error

### ISSUE THREAD

**Issue by Ahmad5112** [Microsoft/AirSim#1752]
I am Trying to run a code for Reinforcement learning and getting the following error how can I resolve the issue?
Traceback (most recent call last):

  File "<ipython-input-1-8f477b229e8d>", line 1, in <module>
    runfile('C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/AirSim/PythonClient/DQN-Train.py', wdir='C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/AirSim/PythonClient')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/AirSim/PythonClient/DQN-Train.py", line 39, in <module>
    env = gym.make(args.env_name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\gym\envs\registration.py", line 167, in make
    return registry.make(id)

  File "C:\ProgramData\Anaconda3\lib\site-packages\gym\envs\registration.py", line 118, in make
    spec = self.spec(id)

  File "C:\ProgramData\Anaconda3\lib\site-packages\gym\envs\registration.py", line 153, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))

UnregisteredEnv: No registered env with id: AirSimEnv-v42

**Comment by madratman** [comment]
Umm, is this an airsim issue in the first place?
You're using a openai gym environment called `AirSimEnv-v42`, which is not our code. 
Please refrain from multiple issues not related to the airsim codebase, and also please do a google search before you open an issue. 
Here you go https://www.google.com/search?safe=active&q=openai+gym+registering+custom+environment
