### ISSUE TITLE
Setting PawnPath causes segmentation fault/access violation

### ISSUE THREAD

**Issue by ab3nd** [microsoft/AirSim#2095]
I am trying to have an invisible, stationary UAV to to serve as a mounted camera in an Unreal Environment. I thought I would be able to do that by setting the vehicle type to ComputerVision, but I can't request images from a ComputerVision vehicle, because it doesn't have API control available (error message at bottom of post). 

I tried editing the stanza to have the VehicleType SimpleFlight, but the DefaultComputerVision pawn, hoping that this would give me a UAV that didn't have a mesh, just cameras. Instead, attempting UE PIE crashes the editor. 

The expected behavior is that the system do something like display an error message, rather than crashing. Additionally, it would be nice to be able to have an invisible UAV that I can get camera images from, but not move around. 

The offending stanza:
```
    "ShackCam": {
      "VehicleType": "SimpleFlight",
      "DefaultVehicleState": "Armed",
      "AutoCreate": true,
      "PawnPath": "DefaultComputerVision",
      "EnableCollisionPassthrogh": false,
      "EnableCollisions": true,
      "AllowAPIAlways": true,
      "RC": {
        "RemoteControlID": 1,
        "AllowAPIWhenDisconnected": true
      },

      "X": -3,
      "Y": 5,
      "Z": -5,

      "UdpPort": 5503,
      "SitlPort": 5504

    }	
```

Error from trying to get a camera image from a ComputerVision vehicle:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./kickoff_demo.py", line 32, in grab_images
    responses = self.client.simGetImages([airsim.ImageRequest("front_center", airsim.ImageType.Scene)], vehicle_name=self.uav_name)
  File "/home/ashultz/.local/lib/python3.5/site-packages/airsim/client.py", line 103, in simGetImages
    responses_raw = self.client.call('simGetImages', requests, vehicle_name)
  File "/home/ashultz/.local/lib/python3.5/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/home/ashultz/.local/lib/python3.5/site-packages/msgpackrpc/future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: function 'simGetImages' (called with 2 arg(s)) threw an exception. The exception contained this information: Vehicle Sim-API for 'ShackCam' is not available. This could either because this is not a simulation or this vehicle does not exist.
```

Complete file:
```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor",
  "ShowLla": true,
  "ShowLosDebugLines": true,
  
  "FastPhysicsEngine": {
    "EnableGroundLock": false
  },
  
  "TimeOfDay": {
	"Enabled": false
  },

  "SubWindows": [
    {"WindowID": 0, "CameraName": "bottom_center", "ImageType": 3, "Visible": false},
    {"WindowID": 1, "CameraName": "bottom_center", "ImageType": 5, "Visible": false},
    {"WindowID": 2, "CameraName": "bottom_center", "ImageType": 0, "Visible": false}    
  ],
  "PawnPaths": {
    "BareboneCar": {"PawnBP": "Class'/AirSim/VehicleAdv/Vehicle/VehicleAdvPawn.VehicleAdvPawn_C'"},
    "DefaultCar": {"PawnBP": "Class'/AirSim/VehicleAdv/SUV/SuvCarPawn.SuvCarPawn_C'"},
    "DefaultQuadrotor": {"PawnBP": "Class'/AirSim/Blueprints/BP_FlyingPawn.BP_FlyingPawn_C'"},
    "DefaultComputerVision": {"PawnBP": "Class'/AirSim/Blueprints/BP_ComputerVisionPawn.BP_ComputerVisionPawn_C'"}
  },
  "Vehicles": {
  	"Solo_0": {
      "VehicleType": "SimpleFlight",
      "DefaultVehicleState": "Armed",
      "AutoCreate": true,
      "PawnPath": "",
      "EnableCollisionPassthrogh": false,
      "EnableCollisions": true,
      "AllowAPIAlways": true,
      "RC": {
        "RemoteControlID": 1,
        "AllowAPIWhenDisconnected": true
      },

      "X": 10,
      "Y": 0,
      "Z": -1,

      "UdpPort": 5505,
      "SitlPort": 5506

    },
	"Orbiter_0": {
      "VehicleType": "SimpleFlight",
      "DefaultVehicleState": "Armed",
      "AutoCreate": true,
      "PawnPath": "",
      "EnableCollisionPassthrogh": false,
      "EnableCollisions": true,
      "AllowAPIAlways": true,
      "RC": {
        "RemoteControlID": 0,
        "AllowAPIWhenDisconnected": true
      },

      "X": 0,
      "Y": 0,
      "Z": -1,

      "UdpPort": 5499,
      "SitlPort": 5500

    },
    "Orbiter_1": {
      "VehicleType": "SimpleFlight",
      "DefaultVehicleState": "Armed",
      "AutoCreate": true,
      "PawnPath": "",
      "EnableCollisionPassthrogh": false,
      "EnableCollisions": true,
      "AllowAPIAlways": true,
      "RC": {
        "RemoteControlID": 0,
        "AllowAPIWhenDisconnected": true
      },

      "X": 5,
      "Y": 0,
      "Z": -1,

      "UdpPort": 5501,
      "SitlPort": 5502

    },
    "ShackCam": {
      "VehicleType": "SimpleFlight",
      "DefaultVehicleState": "Armed",
      "AutoCreate": true,
      "PawnPath": "DefaultComputerVision",
      "EnableCollisionPassthrogh": false,
      "EnableCollisions": true,
      "AllowAPIAlways": true,
      "RC": {
        "RemoteControlID": 1,
        "AllowAPIWhenDisconnected": true
      },

      "X": -3,
      "Y": 5,
      "Z": -5,

      "UdpPort": 5503,
      "SitlPort": 5504

    }	
  },

  "OriginGeopoint": {
    "Latitude": 35.763922,
    "Longitude": -120.770021,
    "Altitude": 36
  },

  "CameraDefaults": {
	  "CaptureSettings": [
	    {
	      "ImageType": 0,
	      "Width": 1280,
	      "Height": 720,
	      "FOV_Degrees": 28,
	      "MotionBlurAmount": 0    
	    },
	    {
	      "ImageType": 2,
	      "Width": 1280,
	      "Height": 720,
	      "FOV_Degrees": 28,
	      "MotionBlurAmount": 0    
	    }
	]
  }

}
```

**Comment by jonyMarino** [comment]
Now we have the external fixed cameras
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
