### ISSUE TITLE
Tornado - uncaught exception, closing connection

### ISSUE THREAD

**Issue by lloydrayner** [microsoft/AirSim#2158]
The below error is triggering causing the environment to crash. Any ideas whats causing it / how to fix?

`E0826 15:27:33.302959 123145454710784 iostream.py:554] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/Users/lrayner/PycharmProjects/T1.V1/venvironment/lib/python3.6/site-packages/tornado/iostream.py", line 523, in _handle_events
    self._handle_write()
  File "/Users/lrayner/PycharmProjects/T1.V1/venvironment/lib/python3.6/site-packages/tornado/iostream.py", line 847, in _handle_write
    assert self._write_buffer_size >= 0
AssertionError
E0826 15:27:33.317214 123145454710784 ioloop.py:638] Exception in callback None
Traceback (most recent call last):
  File "/Users/lrayner/PycharmProjects/T1.V1/venvironment/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/lrayner/PycharmProjects/T1.V1/venvironment/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/lrayner/PycharmProjects/T1.V1/venvironment/lib/python3.6/site-packages/tornado/iostream.py", line 523, in _handle_events
    self._handle_write()
  File "/Users/lrayner/PycharmProjects/T1.V1/venvironment/lib/python3.6/site-packages/tornado/iostream.py", line 847, in _handle_write
    assert self._write_buffer_size >= 0
AssertionError`

**Comment by lloydrayner** [comment]
Figured our a workaround, closing issue
