### ISSUE TITLE
The weather API cannot be used

### ISSUE THREAD

**Issue by sbkybhy** [microsoft/AirSim#2230]
**### Config**
UE: 4.18
AirSim: 1.2.0 ,"CityEnviron" engineering，which was downloaded from "https://github.com/microsoft/AirSim/releases/tag/v1.2.0".
OS: Windows 10

**### Issue**
The weather API cannot be used. After unzipping, the document is ready to use. In this project, I can use python to control the car,but I cann't use python API to control weather.
 When I open the project, like the  below picture ( I  have put it into "computer_vision" mode ),
![image](https://user-images.githubusercontent.com/48812520/66271134-1c0a9880-e88d-11e9-9e57-e8d6797bdeba.png)
if I use "python weather.py", it reports errors like this 

"Traceback (most recent call last):
  File "weather.py", line 8, in <module>
    client.simEnableWeather(True)
  File "D:\AirSim\AirSim-master\PythonClient\airsim\client.py", line 82, in simEnableWeather
    return self.client.call('simEnableWeather', enable)
  File "C:\program1\Anaconda3\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "C:\program1\Anaconda3\lib\site-packages\msgpackrpc\future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: server could not find function 'simEnableWeather' with argument count 1."

![image](https://user-images.githubusercontent.com/48812520/66271190-c387cb00-e88d-11e9-8448-a3cd193762da.png)

**### Logs**
[2019.10.07-02.03.24:682][223]LogSlate: Request Window 'CityEnviron (64-bit, PCD3D_SM5)' being destroyed
[2019.10.07-02.03.25:225][223]LogSlate: Window 'CityEnviron (64-bit, PCD3D_SM5)' being destroyed
[2019.10.07-02.03.25:235][223]LogWindowsTextInputMethodSystem: Display: IME system now activated using TSF (搜狗拼音输入法).
[2019.10.07-02.03.25:245][224]LogEngine: All Windows Closed
[2019.10.07-02.03.25:245][224]LogWindows: FPlatformMisc::RequestExit(0)
[2019.10.07-02.03.26:079][225]LogExit: Preparing to exit.
[2019.10.07-02.03.26:079][225]LogMoviePlayer: Shutting down movie player
[2019.10.07-02.03.26:266][225]LogExit: Game engine shut down
[2019.10.07-02.03.26:477][225]LogExit: Object subsystem successfully closed.
[2019.10.07-02.03.26:803][225]LogD3D11RHI: Shutdown
[2019.10.07-02.03.26:803][225]LogD3D11RHI: CleanupD3DDevice
[2019.10.07-02.03.26:827][225]LogD3D11RHI: ~FD3D11DynamicRHI
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module AutomationController (180)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module AutomationWorker (178)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module AIModule (176)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module GameplayDebugger (175)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module WmfMediaFactory (172)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module OpenExrWrapper (170)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module ImgMediaFactory (168)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module AvfMediaFactory (166)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module CharacterAI (164)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module SessionServices (162)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module MovieSceneTracks (160)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module MovieScene (158)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module GeometryCache (156)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module StreamingPauseRendering (154)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module AnalyticsET (152)
[2019.10.07-02.03.26:827][225]LogModuleManager: Shutting down and abandoning module ProfilerService (150)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module TaskGraph (148)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module SteamVRController (146)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module ProceduralMeshComponent (144)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module OculusInput (142)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module MobilePatchingUtils (140)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module CustomMeshComponent (138)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module CableComponent (136)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module ArchVisCharacter (134)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module AndroidPermission (132)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module ActorSequence (128)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module MediaCompositing (126)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module HTML5Networking (124)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module SplinePathInfo (122)
[2019.10.07-02.03.27:030][225]LogModuleManager: Shutting down and abandoning module NativizedAssets (120)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module RawInput (118)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module CityEnviron (116)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module RuntimePhysXCooking (114)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module LocationServicesBPLibrary (112)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module ImmediatePhysics (110)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module UdpMessaging (108)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module TcpMessaging (106)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module FacialAnimation (104)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module LightPropagationVolumeRuntime (102)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module Paper2D (100)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module AirSim (98)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module SubstanceCore (96)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module PhysXVehicles (94)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module WindowsMoviePlayer (92)
[2019.10.07-02.03.27:031][225]LogModuleManager: Shutting down and abandoning module WmfMedia (90)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module ImgMedia (88)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module PacketHandler (86)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module ClothingSystemRuntime (84)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module MediaAssets (82)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module Overlay (80)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module UMG (78)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module SlateReflector (76)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module Slate (74)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module MRMesh (72)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module Messaging (70)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module HeadMountedDisplay (68)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module XAudio2 (66)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module Networking (64)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module Core (60)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module LevelSequence (58)
[2019.10.07-02.03.27:033][225]LogModuleManager: Shutting down and abandoning module Media (56)
[2019.10.07-02.03.27:040][225]LogModuleManager: Shutting down and abandoning module ImageWrapper (52)
[2019.10.07-02.03.27:040][225]LogModuleManager: Shutting down and abandoning module InputCore (50)
[2019.10.07-02.03.27:040][225]LogModuleManager: Shutting down and abandoning module PhysXCooking (48)
[2019.10.07-02.03.27:040][225]LogModuleManager: Shutting down and abandoning module SteamVR (46)
[2019.10.07-02.03.27:040][225]LogModuleManager: Shutting down and abandoning module OculusHMD (44)
[2019.10.07-02.03.27:040][225]LogModuleManager: Shutting down and abandoning module ExampleDeviceProfileSelector (42)
[2019.10.07-02.03.27:040][225]LogModuleManager: Shutting down and abandoning module AppleARKit (40)
[2019.10.07-02.03.27:040][225]LogModuleManager: Shutting down and abandoning module AugmentedReality (39)
[2019.10.07-02.03.27:040][225]LogModuleManager: Shutting down and abandoning module OnlineSubsystem (34)
[2019.10.07-02.03.27:040][225]LogModuleManager: Shutting down and abandoning module HTTP (33)
[2019.10.07-02.03.27:040][225]LogHttp: Display: Http module shutting down, but needs to wait on 1 outstanding Http requests:
[2019.10.07-02.03.27:040][225]LogHttp: Display: 	verb=[POST] url=[https://datarouter.ol.epicgames.com/datarouter/api/v1/public/data?SessionID=%7B76D0152E-4408-A30A-FF8F-F9A9DB027063%7D&AppID=UEGame.Rocket.Release%7C31B5190A4480D45B3B922AA7978766A9%7CUE4Game&AppVersion=4.18.3-3832480%2B%2B%2BUE4%2BRelease-4.18&UserID=ANON-%7BF5D7DC60-4B98-97DF-6DD7-BD9402410BC0%7D%7C%7C&AppEnvironment=datacollector-binary&UploadType=eteventstream] status=Processing
[2019.10.07-02.03.27:043][225]LogModuleManager: Shutting down and abandoning module SSL (32)
[2019.10.07-02.03.27:043][225]LogModuleManager: Shutting down and abandoning module ShaderCore (28)
[2019.10.07-02.03.27:043][225]LogModuleManager: Shutting down and abandoning module Landscape (26)
[2019.10.07-02.03.27:043][225]LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (24)
[2019.10.07-02.03.27:043][225]LogModuleManager: Shutting down and abandoning module OpenGLDrv (22)
[2019.10.07-02.03.27:043][225]LogModuleManager: Shutting down and abandoning module D3D11RHI (20)
[2019.10.07-02.03.27:043][225]LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (18)
[2019.10.07-02.03.27:043][225]LogModuleManager: Shutting down and abandoning module Renderer (16)
[2019.10.07-02.03.27:043][225]LogModuleManager: Shutting down and abandoning module Engine (14)
[2019.10.07-02.03.27:044][225]LogModuleManager: Shutting down and abandoning module CoreUObject (12)
[2019.10.07-02.03.27:044][225]LogModuleManager: Shutting down and abandoning module NetworkFile (10)
[2019.10.07-02.03.27:044][225]LogModuleManager: Shutting down and abandoning module CookedIterativeFile (8)
[2019.10.07-02.03.27:044][225]LogModuleManager: Shutting down and abandoning module StreamingFile (6)
[2019.10.07-02.03.27:044][225]LogModuleManager: Shutting down and abandoning module SandboxFile (4)
[2019.10.07-02.03.27:044][225]LogModuleManager: Shutting down and abandoning module PakFile (2)
[2019.10.07-02.03.27:049][225]LogExit: Exiting.
[2019.10.07-02.03.27:050][225]Log file closed, 10/07/19 10:03:27
[CityEnviron.log](https://github.com/microsoft/AirSim/files/3695267/CityEnviron.log)

**### Target**
I want to achieve sun change in four seasons  and rain, snow. I need these scenes.

**Comment by rajat2004** [comment]
Weather API was added after this version was released (https://github.com/microsoft/AirSim/commit/b1260c2c3177c886549a962094f286d6c45aac93)
You'll have to use a later release or master

**Comment by sbkybhy** [comment]
Thank you, I solved the problem.  (*^▽^*)

**Comment by rajat2004** [comment]
@sbkybhy Great! Could you close the issue if the problem has been solved?
