### ISSUE TITLE
Docker build fails with "ModuleNotFoundError: No module named 'skbuild'"

### ISSUE THREAD

**Issue by sjmarotta** [microsoft/AirSim#3197]
When building the AirSim docker image, it gets to the step where it calls `RUN pip3 install airsim` and it fails with the following:

```
#8 2.720 Collecting opencv-contrib-python (from airsim)
#8 3.910   Downloading https://files.pythonhosted.org/packages/2a/ef/6ed8ef6aca8ea9625d6577381dad57762713fd532ad41541054b01f760b3/opencv-contrib-python-4.4.0.46.tar.gz (148.8MB)
#8 63.74     Complete output from command python setup.py egg_info:
#8 63.74     Traceback (most recent call last):
#8 63.74       File "<string>", line 1, in <module>
#8 63.74       File "/tmp/pip-build-bfixydcm/opencv-contrib-python/setup.py", line 9, in <module>
#8 63.74         import skbuild
#8 63.74     ModuleNotFoundError: No module named 'skbuild'
#8 63.74
#8 63.74     ----------------------------------------
#8 64.25 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bfixydcm/opencv-contrib-python/
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c pip3 install airsim]: runc did not terminate sucessfully
```

**Comment by sjmarotta** [comment]
I think I fixed it. The issue was that opencv-contrib-python needed Python 3.8 in order to work. I made some minor changes to my Dockerfile_binary. The second block in that file now looks like this:

```
RUN apt-get update
RUN apt-get install \
	python3.8 \
	python3.8-distutils \
	sudo \
	libglu1-mesa-dev \
	xdg-user-dirs \
	pulseaudio \
	sudo \
	wget \
	x11-xserver-utils \
	-y --no-install-recommends
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN rm get-pip.py
RUN pip3 install setuptools wheel
RUN pip3 install airsim
```
Seems to build now, and I don't see the `skbuild` error anymore.
