### ISSUE TITLE
Failure while creating docker container for Airsim v1.4.0 (No module named 'skbuild')

### ISSUE THREAD

**Issue by RahulSajnani** [microsoft/AirSim#3369]
## Bug report 

- AirSim Version/#commit: v1.4.0
- UE/Unity version: - 
- autopilot version: - 
- OS Version: - 

### What's the issue you encountered?

Failure while building docker container. No module named 'skbuild' while installing opencv-contrib-python

### Settings

Default settings.json.

### How can the issue be reproduced?

1. Create the docker container for Linux using instructions given [here](https://microsoft.github.io/AirSim/docker_ubuntu/)

### Include full error message in text form

Step 6/12 : RUN pip3 install airsim
 ---> Running in b7357d5a8b00
Collecting airsim
  Downloading https://files.pythonhosted.org/packages/7d/30/7665be049ff56d2269f5e736812eb6569762f2cc278f47257addf63bd6af/airsim-1.3.0-py3-none-any.whl
Collecting opencv-contrib-python (from airsim)
  Downloading https://files.pythonhosted.org/packages/42/02/7b2fb0b81266aa3243dd8f392d48db1a206cc9a1856a14228e75c515616e/opencv-contrib-python-4.5.1.48.tar.gz (148.8MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p8bcl6pe/opencv-contrib-python/setup.py", line 10, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-p8bcl6pe/opencv-contrib-python/
The command '/bin/sh -c pip3 install airsim' returned a non-zero code: 1

**What's better than filing an issue? Filing a pull request :).**

**Comment by RahulSajnani** [comment]
I was able to fix this by updating pip version in the docker file and installing scikit-build before installing opencv-contrib-python
