### ISSUE TITLE
Error on python API

### ISSUE THREAD

**Issue by zaeucu** [microsoft/AirSim#3999]
## Bug report 

- AirSim Version/#commit: 1.5.0
- UE/Unity version: 4.27
- autopilot version: N/A
- OS Version: windows 10 64bit
- python 3.7

### What's the issue you encountered?

When i install python API by "pip install airsim", then there is a installing error on utils.py, like below,

        from .utils import *
      File "C:\Users\CW\AppData\Local\Temp\pip-install-wcrhvxg3\airsim_45065bee18cc4683b04341582a5f21f6\airsim\utils.py", line 208
        logging.error(f"Writing PNG file {filename} failed")
                                                          ^
    SyntaxError: invalid syntax
    ----------------------------------------

Also there is same error on several versions.

### Settings

there is no change with default.
### How can the issue be reproduced?

1.  Just pip install airsim
2.

### Include full error message in text form

ERROR: Command errored out with exit status 1:
     command: 'c:\users\cw\anaconda3\envs\airsim\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\CW\\AppData\\Local\\Temp\\pip-install-wcrhvxg3\\airsim_45065bee18cc4683b04341582a5f21f6\\setup.py'"'"'; __file__='"'"'C:\\Users\\CW\\AppData\\Local\\Temp\\pip-install-wcrhvxg3\\airsim_45065bee18cc4683b04341582a5f21f6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\CW\AppData\Local\Temp\pip-pip-egg-info-om4pznve'
         cwd: C:\Users\CW\AppData\Local\Temp\pip-install-wcrhvxg3\airsim_45065bee18cc4683b04341582a5f21f6\
    Complete output (12 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\CW\AppData\Local\Temp\pip-install-wcrhvxg3\airsim_45065bee18cc4683b04341582a5f21f6\setup.py", line 2, in <module>
        from airsim import __version__
      File "C:\Users\CW\AppData\Local\Temp\pip-install-wcrhvxg3\airsim_45065bee18cc4683b04341582a5f21f6\airsim\__init__.py", line 1, in <module>
        from .client import *
      File "C:\Users\CW\AppData\Local\Temp\pip-install-wcrhvxg3\airsim_45065bee18cc4683b04341582a5f21f6\airsim\client.py", line 3, in <module>
        from .utils import *
      File "C:\Users\CW\AppData\Local\Temp\pip-install-wcrhvxg3\airsim_45065bee18cc4683b04341582a5f21f6\airsim\utils.py", line 208
        logging.error(f"Writing PNG file {filename} failed")
                                                          ^
    SyntaxError: invalid syntax

**What's better than filing an issue? Filing a pull request :).**

**Comment by LittleTimeWxk** [comment]
I meet the same problem.
