### ISSUE TITLE
Docker error while building with CMake

### ISSUE THREAD

**Issue by Harsh188** [microsoft/AirSim#4957]
## Description

I'm trying to build the Docker image following the instructions [here](https://microsoft.github.io/AirSim/docker_ubuntu/#binaries). 

I solved issues with PUBKEY using the following suggestions:
```
RUN rm /etc/apt/sources.list.d/cuda.list
RUN rm /etc/apt/sources.list.d/nvidia-ml.list
```

Here is my error output:
```
1358.1   Note: Class cv::Feature2D has more than 1 base class (not supported by Python C extensions)
1358.1         Bases:  cv::Algorithm, cv::class, cv::Feature2D, cv::Algorithm
1358.1         Only the first base class will be used
1358.1   Note: Class cv::detail::GraphCutSeamFinder has more than 1 base class (not supported by Python C extensions)
1358.1         Bases:  cv::detail::GraphCutSeamFinderBase, cv::detail::SeamFinder
1358.1         Only the first base class will be used
1358.1   [ 99%] Built target gen_opencv_python_source
1358.1   [ 99%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
1358.1   In file included from /tmp/pip-install-7y5ll61r/opencv-contrib-python_bf26f86786504c3a81d71bc915dd8039/opencv/modules/python/src2/cv2.cpp:5:0:
1358.1   /tmp/pip-install-7y5ll61r/opencv-contrib-python_bf26f86786504c3a81d71bc915dd8039/opencv/modules/python/src2/cv2.hpp:20:10: fatal error: Python.h: No such file or directory
1358.1    #include <Python.h>
1358.1             ^~~~~~~~~~
1358.1   compilation terminated.
1358.1   modules/python3/CMakeFiles/opencv_python3.dir/build.make:75: recipe for target 'modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o' failed
1358.1   make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o] Error 1
1358.1   CMakeFiles/Makefile2:5463: recipe for target 'modules/python3/CMakeFiles/opencv_python3.dir/all' failed
1358.1   make[1]: *** [modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
1358.1   Makefile:165: recipe for target 'all' failed
1358.1   make: *** [all] Error 2
1358.1   Traceback (most recent call last):
1358.1     File "/tmp/pip-build-env-eymbtx3s/overlay/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 642, in setup
1358.1       cmkr.make(make_args, install_target=cmake_install_target, env=env)
1358.1     File "/tmp/pip-build-env-eymbtx3s/overlay/lib/python3.6/site-packages/skbuild/cmaker.py", line 679, in make
1358.1       self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
1358.1     File "/tmp/pip-build-env-eymbtx3s/overlay/lib/python3.6/site-packages/skbuild/cmaker.py", line 711, in make_impl
1358.1       "An error occurred while building with CMake.\n"
1358.1   
1358.1   An error occurred while building with CMake.
1358.1     Command:
1358.1       /tmp/pip-build-env-eymbtx3s/overlay/lib/python3.6/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
1358.1     Install target:
1358.1       install
1358.1     Source directory:
1358.1       /tmp/pip-install-7y5ll61r/opencv-contrib-python_bf26f86786504c3a81d71bc915dd8039
1358.1     Working directory:
1358.1       /tmp/pip-install-7y5ll61r/opencv-contrib-python_bf26f86786504c3a81d71bc915dd8039/_skbuild/linux-x86_64-3.6/cmake-build
1358.1   Please check the install target is valid and see CMake's output for more information.
1358.1   ----------------------------------------
1358.1   ERROR: Failed building wheel for opencv-contrib-python
1358.1   Building wheel for tornado (setup.py): started
1358.4   Building wheel for tornado (setup.py): finished with status 'done'
1358.4   Created wheel for tornado: filename=tornado-4.5.3-cp36-cp36m-linux_x86_64.whl size=420786 sha256=3cdd213c7c1f42275c80e3c8f844f83a16a6425251877ee7ce5bc8a8023ebf7e
1358.4   Stored in directory: /root/.cache/pip/wheels/7c/26/a6/8fc2a26547829568bcafabbabe61ea5f9c449f97be752af46a
1358.4   Building wheel for msgpack-python (setup.py): started
1358.6   Building wheel for msgpack-python (setup.py): finished with status 'done'
1358.6   Created wheel for msgpack-python: filename=msgpack_python-0.5.6-cp36-cp36m-linux_x86_64.whl size=10418 sha256=e9d8017e32cb076da9eddb142b8e9e32beb9ed83e736003e9b19169a55b1a033
1358.6   Stored in directory: /root/.cache/pip/wheels/d5/bc/14/cd44eeb567de86911dd5ca37e718e67044d03b6128eb80ef1b
1358.6 Successfully built airsim msgpack-rpc-python tornado msgpack-python
1358.6 Failed to build opencv-contrib-python
1358.6 ERROR: Could not build wheels for opencv-contrib-python, which is required to install pyproject.toml-based projects
------
Dockerfile_binary:16
--------------------
  15 |     
  16 | >>> RUN python3 -m pip install --upgrade pip && \
  17 | >>>     pip3 install setuptools wheel && \
  18 | >>>     pip3 install airsim
  19 |     
--------------------
```

**Comment by Rainoxer** [comment]
Hi, did you find a solution?
