### ISSUE TITLE
AttributeError: 'numpy.int32' object has no attribute 'to_msgpack'

### ISSUE THREAD

**Issue by lo2aayy** [Microsoft/AirSim#681]
Hey,

I am using computer vision mode to collect data using AirSim and I'm getting the following error:
" AttributeError: 'numpy.int32' object has no attribute 'to_msgpack' "

which is triggered by the following line:

Traceback (most recent call last):
 

> Traceback (most recent call last):
  File "cv_dataset.py", line 142, in <module>
    client.simSetPose(Pose(Vector3r(x, y, z), AirSimClientBase.toQuaternion(toRadians(-Cam_Tilt), 0, toRadians(-Cam_Pan))), True)
  File "C:\Users\abdelgal\Desktop\DeepLanding\AirSimAIS\AirSimClient.py", line 265, in simSetPose
    self.client.call('simSetPose', pose, ignore_collison)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpackrpc\session.py", line 51, in send_request
    self._transport.send_message([message.REQUEST, msgid, method, args])
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpackrpc\transport\tcp.py", line 94, in send_message
    sock.send_message(message, callback)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpackrpc\transport\tcp.py", line 19, in send_message
    self._stream.write(self._packer.pack(message), callback=callback)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpack\fallback.py", line 738, in pack
    self._pack(obj)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpack\fallback.py", line 726, in _pack
    self._pack(obj[i], nest_limit - 1)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpack\fallback.py", line 726, in _pack
    self._pack(obj[i], nest_limit - 1)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpack\fallback.py", line 730, in _pack
    nest_limit - 1)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpack\fallback.py", line 828, in _fb_pack_map_pairs
    self._pack(v, nest_limit - 1)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpack\fallback.py", line 730, in _pack
    nest_limit - 1)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpack\fallback.py", line 828, in _fb_pack_map_pairs
    self._pack(v, nest_limit - 1)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpack\fallback.py", line 732, in _pack
    obj = self._default(obj)
  File "C:\Users\abdelgal\AppData\Local\Programs\Python\Python36-32\lib\site-packages\msgpackrpc\transport\tcp.py", line 12, in <lambda>
    self._packer = msgpack.Packer(encoding=encodings[0], default=lambda x: x.to_msgpack())
AttributeError: 'numpy.int32' object has no attribute 'to_msgpack'

I'm using python 3.6 and numpy 1.13

**Comment by sytelus** [comment]
I tried out call to `client.simSetPose` and it seems to work fine. I think the problem might be that you have updated your repo but not your PythonClient code. I would suggest to copy PythonClient folder from latest version and try it out.

**Comment by koshyviv** [comment]
Hi, I'm facing the same issue as @lo2aayy. I did check and am using the latest code/repo.
Any suggestions?

**Comment by zhangjunwang** [comment]
hi, I have the same problem with you. I copy PythonClient folder from latest version, but it does not work. Could you tell me how to solve it? thanks

`Traceback (most recent call last):
  File "pponew.py", line 325, in <module>
    client.setCarControls(car_controls)
  File "/home/zjw/.local/lib/python3.5/site-packages/airsim/client.py", line 305, in setCarControls
    self.client.call('setCarControls', controls, vehicle_name)
  File "/home/zjw/.local/lib/python3.5/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/home/zjw/.local/lib/python3.5/site-packages/msgpackrpc/session.py", line 51, in send_request
    self._transport.send_message([message.REQUEST, msgid, method, args])
  File "/home/zjw/.local/lib/python3.5/site-packages/msgpackrpc/transport/tcp.py", line 94, in send_message
    sock.send_message(message, callback)
  File "/home/zjw/.local/lib/python3.5/site-packages/msgpackrpc/transport/tcp.py", line 19, in send_message
    self._stream.write(self._packer.pack(message), callback=callback)
  File "msgpack/_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 263, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 263, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 277, in msgpack._packer.Packer._pack
  File "/home/zjw/.local/lib/python3.5/site-packages/msgpackrpc/transport/tcp.py", line 12, in <lambda>
    self._packer = msgpack.Packer(encoding=encodings[0], default=lambda x: x.to_msgpack())
AttributeError: 'numpy.float32' object has no attribute 'to_msgpack'
`
